// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pczdjmdvcqbtrugepfcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjemRqbWR2Y3FidHJ1Z2VwZmNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzMzUwOTYsImV4cCI6MjA0OTkxMTA5Nn0.vBKUFryttksYm-RBQLg9cmNSeG-1OFNktjXLcqJFstM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);